baseURL: 'https://junbread.win'
languageCode: 'ko-kr'
title: 'JunbreadğŸ¥'
theme: 'PaperMod'
params:
  env: production
  disableThemeToggle: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments:
    provider: "giscus"
    commentable:
      - post: true

  homeInfoParams:
    title: "Junbread Dev Blog"
    content: "ê°œë°œ&ìƒˆë°œğŸ’»"
  socialIcons:
    - name: "github"
      url: "https://github.com/junbread"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/junhyun-kim-967068182/"
    - name: "rss"
      url: "/index.xml"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: categories
      name: ì¹´í…Œê³ ë¦¬
      url: /categories/
      weight: 20
    - identifier: archives
      name: ì•„ì¹´ì´ë¸Œ
      url: /archives/
      weight: 30
    - identifier: tags
      name: íƒœê·¸
      url: /tags/
      weight: 40
    - identifier: search
      name: ê²€ìƒ‰
      url: /search/
      weight: 50
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true